server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:amaranth.phature.name.p12
    key-store-password: amaranth.phature.name
    key-alias: amaranth.phature.name
spring:
  application:
    name: amaranth-architecture-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: amaranth-test-business
          uri: lb://amaranth-test-business
          predicates:
            - Path=/amaranth/test/business/**
          filters:
            - StripPrefix=0
  profiles:
    include: amaranth-architecture-configuration