@startuml class-permission

class PermisionToken {
    - String id
    - User user
    - User proxy
}

class User {
    - String id
    - List<Group> groups
    - List<Role> roles
}

PermisionToken *-- User

class Role {
    - String id
    - List<Menu> menus
}

User *-- Role

class Menu {
    - String id
    - List<Page> pages
}

Role *-- Menu
Menu *-- Menu

class Page {
    - String id
    - List<Component>  components
}

Menu *-- Page

class Component {
    - String id
    - List<Function>  functions
}

Page *-- Component

class Function {
    - String id
}

Component *-- Function

class Group {
    - String id
}

User *-- Group

class Datum {
    - String userId
    - String groupId
    - Boolean userRead
    - Boolean userWrite
    - Boolean groupRead
    - Boolean groupWrite
    - Boolean everyoneRead
    - Boolean everyoneWrite
}

Group o-- Datum

    @enduml