@startuml class-user

class User {
    - String id
    - String name
    - Boolean validity
    - UserType type
    - List<Account> accounts
    - List<Credential> credentials
}

enum UserType {
    - String id
    - String name
}

User *-- UserType

class Service {
    - String type = "S"
}

class Human {
    - String type = "H"
}

class External {
    - String type = "E"
}

User <|-- Service
User <|-- Human
User <|-- External

class Account {
    - String id
    - String name
    - String userId
    - PasswordType passwordType
}

class Password {
    - String id
    - String value
    - String userId
    - String accountId
    - PasswordType passwordType
}

User *-- Account
User *-- Password

enum PasswordType {
    - String id
    - String name
}

Account *-- PasswordType
Password *-- PasswordType

@enduml