@startuml sequence-session

participant User
participant Service
participant Portal

User --> Service : 请求页面
User <-- Service : 响应页面，返回门户跳转地址

User --> Portal : 请求签入
Portal --> Portal : 身份认证
User <-- Portal : 响应签入，返回门户访问令牌

User --> Portal : 请求服务跳转令牌，提供门户访问令牌
Portal --> Portal : 验证门户访问令牌
Portal --> Service : 请求服务跳转令牌，提供会话、用户等数据
Portal <-- Service : 响应服务跳转令牌，返回服务跳转令牌
User <-- Portal : 响应服务跳转令牌，返回服务跳转令牌

User --> Service : 请求页面，提供服务跳转令牌
Service --> Service : 验证服务跳转令牌，处理会话数量，处理令牌黑名单
User <-- Service : 响应页面，返回服务访问令牌

User --> Service : 请求页面，提供服务访问令牌
Service --> Service : 验证服务访问令牌
User <-- Service : 响应页面，返回数据

User --> Service : 请求更新服务访问令牌，提供服务访问令牌
Service --> Service : 验证服务访问令牌，更新服务访问令牌时间戳
User <-- Service : 响应页面，返回新的服务访问令牌

User --> Portal : 请求更新门户访问令牌，提供门户访问令牌
Portal --> Portal : 验证门户访问令牌，更新门户访问令牌时间戳
User <-- Portal : 响应页面，返回新的门户访问令牌

User --> Portal : 请求签出，提供门户访问令牌
Portal --> Portal : 验证门户访问令牌
Portal --> Service : 请求签出，提供会话数据
Service --> Service : 处理令牌黑名单
Portal --> Service : 响应签出
User <-- Portal : 响应签出

@enduml