eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8761
spring:
  application:
    name: amaranth-architecture-discovery
  profiles:
    include: amaranth-architecture-configuration